name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${HOME}/firebase-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ HOME }}/firebase-key.json

      - name: Install Dependencies for Functions
        working-directory: public/main_page/pdf/pdf_to_image/functions
        run: npm install

      - name: Deploy Hosting and Functions
        run: |
          firebase deploy --only hosting,functions --project filebae-13715 --token "$(cat ${HOME}/firebase-key.json)"

      - name: Commit tools.json with GH_PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add public/tools.json
          git commit -m "Update tools.json" || echo "No changes to commit"
          git push