name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/firebase-key.json
          firebase login:ci --token "$(cat ${HOME}/firebase-key.json)"
          firebase use --add filebae-13715 --token "$(cat ${HOME}/firebase-key.json)"

      - name: Install project dependencies (if needed)
        run: npm install || echo "No dependencies to install"

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting,functions --project filebae-13715 --token "$(cat ${HOME}/firebase-key.json)"
