name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - '.github/workflows/firebase-hosting.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Setup Service Account
        run: |
          mkdir -p ~/.config/gcloud/
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > ~/.config/gcloud/application_default_credentials.json
          
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ~/.config/gcloud/application_default_credentials.json
