name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${HOME}/firebase-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ HOME }}/firebase-key.json

      - name: Install Function Dependencies
        working-directory: functions
        run: npm install

      - name: Deploy Hosting + Functions
        run: |
          firebase deploy --only hosting,functions --project filebae-13715 --token "$(cat ${HOME}/firebase-key.json)"
